title: Diary of a Windows developer 


baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://qmatteoq.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

gems:
  - jekyll-paginate

paginate: 3
paginate_path: "/page:num/"


# social
author: "Matteo Pagani"
image: /thumbnail-jumbo.png
twitter:
  username: qmatteoq
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins